### ISSUE TITLE
APP打包后图片位置异常

### ISSUE THREAD

**Issue by netzhouxiang** [apache/incubator-weex-site#557]
我用了EEUI界面开发 weex app，出现以下问题，在打包后，图片出现随机起飞的情况：  
请问是什么导致，还是weex渲染机制问题  

![image](https://user-images.githubusercontent.com/20832795/69329264-b8e19380-0c8b-11ea-9bf4-c9586b95ad66.png)
![image](https://user-images.githubusercontent.com/20832795/69329277-be3ede00-0c8b-11ea-9f42-42aa2080c844.png)
![image](https://user-images.githubusercontent.com/20832795/69329304-cac33680-0c8b-11ea-9446-596b54bc1fe6.png)

**Comment by YorkShen** [comment]
如果你对 EEUI 有疑问，请在 EEUI 相关的 Github 仓库下询问。

**Comment by netzhouxiang** [comment]
eeui说是 weex 渲染问题；

**Comment by YorkShen** [comment]
@netzhouxiang If you use any third party plugin, then use it at your own risk.

**Public or private harassment** is not allowed due to [CODE OF CONDUCT](https://github.com/apache/incubator-weex/blob/master/CODE_OF_CONDUCT.md), I will not waste my time to respond you due to your inapproriate behaviour.
